<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Shipper_model extends CI_Model
{

    public $table = 't03_shipper';
    public $id = 'idshipper';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('idshipper', $q);
	$this->db->or_like('Kode', $q);
	$this->db->or_like('Nama', $q);
	$this->db->or_like('Alamat', $q);
	$this->db->or_like('Kota', $q);
	$this->db->or_like('created_at', $q);
	$this->db->or_like('updated_at', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('idshipper', $q);
	$this->db->or_like('Kode', $q);
	$this->db->or_like('Nama', $q);
	$this->db->or_like('Alamat', $q);
	$this->db->or_like('Kota', $q);
	$this->db->or_like('created_at', $q);
	$this->db->or_like('updated_at', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    /**
     * get new Kode Shipper
     */
    function getNewKode($idshipper)
    {
        $row = $this->get_by_id($idshipper);
        // $kode = $row->Kode;
        // $lenKode = strlen($row->Kode);
        $this->db->order_by('Kode', 'desc');
        $this->db->limit(1);
        $row = $this->db->get($this->table)->row();
        if ($row) {
            /**
             * data yang dicari :: ditemukan
             */
            $value = $row->Kode;
            // $sLastKode = intval(substr($value, 3, 3)); // ambil 3 digit terakhir
            $sLastKode = intval(substr($value, 1, 4)); // ambil 4 digit terakhir
            $sLastKode = intval($sLastKode) + 1; // konversi ke integer, lalu tambahkan satu
            $sNextKode = "S" . sprintf('%04s', $sLastKode); // format hasilnya dan tambahkan prefix
            if (strlen($sNextKode) > 5) {
                $sNextKode = "S9999";
            }
        } else {
            /**
             * data yang dicari :: tidak ditemukan, maka
             * kode-induk + 1   => untuk level 2
             *            + 01  => untuk level 3
             *            + 001 = > untuk level 4 dan 5
             */
            $sNextKode = "S0001";
        }
        return $sNextKode;
    }

}

/* End of file Shipper_model.php */
/* Location: ./application/models/Shipper_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-01-03 23:40:30 */
/* http://harviacode.com */
